# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'AzLinux DCR Public (8e037ad4-618f-4466-8bc8-5099d41ac15b)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az rest \
          --method GET \
          --url "https://management.azure.com/subscriptions/{subscription-id}/resources" \
          --url-parameters api-version=2020-06-01 \$expand=createdTime \$select=name,createdTime
